### ISSUE TITLE
Use SwiftCheck for Unit Testing ✨

### ISSUE THREAD

**Issue by RuiAAPeres** [Velhotes/Vinyl#14]
We should use of [SwiftCheck](https://github.com/typelift/SwiftCheck) or something similar for our tests, so they are more robust. What do you think @CodaFi?

**Comment by CodaFi** [comment]
Doooo it.

**Comment by rubenroques** [comment]
Should we use [Carthage](https://github.com/Carthage/Carthage/) to integrate [SwiftCheck](https://github.com/typelift/SwiftCheck)?

**Comment by dmcrodrigues** [comment]
:+1:

**Comment by CodaFi** [comment]
Any way you want to do it works.  We use `carthage` with `--use-submodules` for the best of both worlds.
