### ISSUE TITLE
Manually creating Vinyl

### ISSUE THREAD

**Issue by RuiAAPeres** [Velhotes/Vinyl#2]
It should be possible to create a `Vinyl`, besides passing a path to one. This gives a great deal of flexibility in the API.

```swift
let songs: [Song] = ...
let vinyl = Vinyl(songs: songs)
let turntable = Turntable(vinyl: vinyl)
```

**Comment by SandroMachado** [comment]
+1

**Comment by dmcrodrigues** [comment]
I agree, this flexibility can be extremely helpful. 

And I think this could be flexible in a way where you can test network failures like receiving an error with a specific `NSURLErrorDomain`, e.g. `NSURLErrorTimedOut`.
