### ISSUE TITLE
Generate releases on Travis

### ISSUE THREAD

**Issue by dmcrodrigues** [Velhotes/Vinyl#44]
We could use Travis to manage our releases, every tag created automatically triggers a build on Travis which can then build and deploy our frameworks to GitHub.

Reference: [GitHub Releases Uploading](https://docs.travis-ci.com/user/deployment/releases).

**Comment by dmcrodrigues** [comment]
@RuiAAPeres What do you think about doing this?

**Comment by RuiAAPeres** [comment]
Oh that's pretty awesome!

**Comment by dmcrodrigues** [comment]
:+1:
