### ISSUE TITLE
Document Recording feature

### ISSUE THREAD

**Issue by mluisbrown** [Velhotes/Vinyl#66]
Now that recording has been implemented, its use should be documented in the README :)

I'll do this when I get time.

**Comment by brentleyjones** [comment]
Until I found this issue I had assumed there was no recording and was going to have to go with DVR. Having it be even lightly documented in the README would help immensely.

**Comment by mluisbrown** [comment]
Sorry @brentleyjones, it's my fault for letting this drag on for so long after I implemented recording. The documentation for recording will be included in the Swift 3 PR #67. You can take a look at the docs  for recording in my Swift 3 branch: https://github.com/mluisbrown/Vinyl/blob/mb/swift3/README.md#recording
For Swift 2.x there is little difference other than the renaming of `URLRequest` and `URLSession`

**Comment by brentleyjones** [comment]
Awesome!

**Comment by mluisbrown** [comment]
Resolved by #67, so closing.
