### ISSUE TITLE
Swift 3.1 warnings

### ISSUE THREAD

**Issue by brentleyjones** [Velhotes/Vinyl#72]
> Vinyl/Response.swift:63:41: String interpolation produces a debug description for an optional value; did you mean to make this explicit?

> Vinyl/Response.swift:64:43: String interpolation produces a debug description for an optional value; did you mean to make this explicit?

> Vinyl/Response.swift:66:18: String interpolation produces a debug description for an optional value; did you mean to make this explicit?

**Comment by mluisbrown** [comment]
I've had similar warnings in other projects. It's a very straightforward fix. I'll do it shortly.

**Comment by brentleyjones** [comment]
Awesome, thanks!

**Comment by mluisbrown** [comment]
#73 addresses this and is just waiting to be reviewed and merged :)

**Comment by brentleyjones** [comment]
Merged. Thanks!
