### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by millcity** [Velhotes/Vinyl#77]
Hi, I'm migrating my project to Swift 4 and am getting an error from Carthage when I try to pull in Vinyl saying I'm using an incompatible version of Swift. Any plans to build the Vinyl framework with Swift 4?

**Comment by jane-austin** [comment]
This should be fairly straightforward (as a task for me 😅). When do you need this?

**Comment by millcity** [comment]
Excellent, ideally if we could get it within the next week that would be great. We can delay moving to Swift 4 if you need more time though. Thanks for the quick response :)
